# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

RUN apt-get update
RUN apt-get install -y git

ARG REPO_URL=""
ARG PORT="8000"

RUN git clone ${REPO_URL} --depth 1 ./django_app
WORKDIR ./django_app

RUN pip install -r requirements.txt


CMD [ "python3", "manage.py" , "runserver", "0.0.0.0:8000"]