# syntax=docker/dockerfile:1

FROM python:3-slim-buster

RUN apt-get update
RUN apt-get install -y git

RUN git clone https://github.com/HemendraSingh/Python-Flask-HelloWorld.git --depth 1 ./flask_app
WORKDIR ./flask_app

RUN pip install -r requirements.txt

ENV FLASK_RUN_PORT=5000
ENV FLASK_RUN_HOST=0.0.0.0

CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]